# Generated by Django 6.0.3 on 2026-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Marek B', max_length=200),
            preserve_default=False,
        ),
    ]
