# Generated by Django 6.0.4 on 2026-04-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_posttag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posttag',
            table='posts_tags',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
