# Generated by Django 6.0.4 on 2026-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posttag_table_alter_tag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagS',
            field=models.ManyToManyField(to='blog.tag'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
