# Generated by Django 6.0.4 on 2026-04-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags_delete_posttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tagS',
            new_name='tags',
        ),
    ]
