# Generated by Django 6.0.4 on 2026-04-20 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd0a14c1-7f27-4901-855a-5340c52c5742'), primary_key=True, serialize=False),
        ),
    ]
