# Generated by Django 6.0.3 on 2026-04-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ogloszenia',
            table='ogloszenia',
        ),
    ]
