# Generated by Django 6.0.4 on 2026-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='cars/')),
                ('owner_website', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
