# Generated by Django 6.0.4 on 2026-04-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.dealer'),
            preserve_default=False,
        ),
    ]
